# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_type', models.CharField(max_length=100)),
                ('due_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Elk_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=20)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('contact_email_address', models.CharField(max_length=100)),
                ('inquiry_title', models.CharField(max_length=250)),
                ('inquiry_content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Elk_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elk_member_type', models.CharField(max_length=50)),
                ('elk_first_name', models.CharField(max_length=20)),
                ('elk_last_name', models.CharField(max_length=50)),
                ('elk_member_email_address', models.CharField(max_length=100)),
                ('elk_member_nickname', models.CharField(max_length=30)),
                ('elk_member_since_date', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Elk_NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_subscriber', models.CharField(max_length=1)),
                ('subscriber_first_name', models.CharField(max_length=20)),
                ('subscriber_last_name', models.CharField(max_length=50)),
                ('subscriber_email_address', models.CharField(max_length=100)),
                ('newsletter_title', models.CharField(max_length=200)),
                ('archive_urls', models.CharField(max_length=100)),
                ('archive_date', models.DateTimeField(verbose_name='elk newsletter date')),
            ],
        ),
        migrations.CreateModel(
            name='Elk_Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=100)),
                ('photo_description', models.CharField(max_length=300)),
                ('elk_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franklinlodge.Elk_Member')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(verbose_name='date of event')),
            ],
        ),
        migrations.CreateModel(
            name='Membership_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospective_member_first_name', models.CharField(max_length=20)),
                ('prospective_member_last_name', models.CharField(max_length=50)),
                ('prospective_member_email_address', models.CharField(max_length=100)),
                ('prospective_member_address', models.CharField(max_length=300)),
                ('prospective_membership_type', models.CharField(max_length=100)),
            ],
        ),
    ]
